# Configuration for Upptime
owner: shruthie2  # Your GitHub username
repo: uptime       # Repository name should match your actual repo

# List of websites to monitor
sites:
  - name: shruthiprom1
    url: https://shruthiprom1.glitch.me
  - name: kavyaprom1
    url: https://kavyaprom1.glitch.me
  - name: snehaProm1
    url: https://snehaProm1.glitch.me
  - name: meghanaprom1
    url: https://meghanaprom1.glitch.me
  - name: ramyaprom01
    url: https://ramyaprom01.glitch.me
  - name: nidhiprom1
    url: https://nidhiprom1.glitch.me
  - name: sowmyaprom1
    url: https://sowmyaprom1.glitch.me
  - name: divyaprom1
    url: https://divyaprom1.glitch.me
  - name: keerthiprom1
    url: https://keerthiprom1.glitch.me
  - name: kavyaprom2
    url: https://kavyaprom2.glitch.me
  - name: arpithaprom1
    url: https://arpithaprom1.glitch.me
  - name: divyaprom2
    url: https://divyaprom2.glitch.me
  - name: sowmyaprom2
    url: https://sowmyaprom2.glitch.me
  - name: shruthiprom02
    url: https://shruthiprom02.glitch.me
  - name: keerthiprom2
    url: https://keerthiprom2.glitch.me
  - name: nidhiprom2
    url: https://nidhiprom2.glitch.me
  - name: meghanaprom2
    url: https://meghanaprom2.glitch.me
  - name: ramyaprom2
    url: https://ramyaprom2.glitch.me
  - name: arpithaprom2
    url: https://arpithaprom2.glitch.me
  - name: snehaprom2
    url: https://snehaprom2.glitch.me
  - name: shruthi1
    url: https://shruthi1.glitch.me
  - name: kavya1
    url: https://kavya1.glitch.me
  - name: sneha1
    url: https://sneha1.glitch.me
  - name: meghana1
    url: https://meghana1.glitch.me
  - name: ramya1
    url: https://ramya1.glitch.me
  - name: nidhi1
    url: https://nidhi1.glitch.me
  - name: sowmya1
    url: https://sowmya1.glitch.me
  - name: divya1
    url: https://divya1.glitch.me
  - name: keerthi1
    url: https://keerthi1.glitch.me
  - name: kavya4
    url: https://kavya4.glitch.me
  - name: arpitha1
    url: https://arpitha1.glitch.me
  - name: divya2
    url: https://divya2.glitch.me
  - name: sowmya2
    url: https://sowmya2.glitch.me
  - name: shruthi2
    url: https://shruthi2.glitch.me
  - name: keerthi2
    url: https://keerthi2.glitch.me
  - name: nidhi2
    url: https://nidhi2.glitch.me
  - name: meghana2
    url: https://meghana2.glitch.me
  - name: ramya2
    url: https://ramya2.glitch.me
  - name: arpitha3
    url: https://arpitha3.glitch.me
  - name: sneha2
    url: https://sneha2.glitch.me

# Status website configuration
status-website:
  # URL path for hosting (since it's GitHub Pages)
  baseUrl: /uptime
  
  # Branding
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: TG Client Status
  theme: dark # Options: light, dark, night
  
  # Introduction section
  introTitle: "TG Client Service Status"
  introMessage: "Real-time monitoring dashboard for all TG client services, powered by **Upptime**"
  
  # Navbar links
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Home
      href: https://github.com/shruthie2

# Workflow configuration
workflowSchedule:
  graphs: "0 0 * * *"       # Generate graphs daily at midnight
  responseTime: "0 23 * * *" # Update response time stats daily at 11pm
  staticSite: "0 1 * * *"    # Update static site daily at 1am
  summary: "0 0 * * *"       # Update summary daily at midnight
  updateTemplate: "0 0 * * *" # Update template daily at midnight
  updates: "0 3 * * *"       # Update dependencies daily at 3am
  uptime: "*/5 * * * *"      # Check uptime every 5 minutes

# Notifications
notifications:
  email:
    - name: TG Team Notifications
      schedule: "daily" # Options: 'live', 'daily', 'weekly'
      notificationText: "Some sites on $OWNER/$REPO are experiencing downtime"
      recipient: "dodieajt@gmail.com"  # Add your email here to enable notifications

# Issue assignments
assignees:
  - shruthie2

# Custom checks (optional)
user-agent: "upptime-bot"

# Security headers (optional, HSTS configuration)
commitMessages:
  commitAuthorName: "Upptime Bot"
  commitAuthorEmail: "upptime@shruthie2.github.io"

# API and badge options
badgeUrl: https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/$OWNER/$REPO/master/api/uptime.json

httpConfig:
  timeout: 30000              # Request timeout in milliseconds
  retries: 3                  # Number of retries on failure
  delayBetweenRetries: 2000   # Delay between retries in milliseconds

# Custom status codes handling
successStatuses:
  - 200-299                  # Default success range
  - 429                      # Rate limiting is not considered downtime

# Rate limiting protection
rateLimiting:
  enabled: true
  maxRequests: 60            # Maximum requests per minute
