name: Uptime CI 6

on:
  schedule:
    - cron: "10,25,40,55 * * * *"
  repository_dispatch:
    types: [uptime]
  workflow_dispatch:

jobs:
  release:
    name: Check status (Group 6)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check endpoint status
        uses: upptime/uptime-monitor@v1.39.0
        with:
          command: "update"
        env:
          GH_PAT: ${{ secrets.GH_PAT || github.token }}